### ISSUE TITLE
blast.py KeyError

### ISSUE THREAD

**Issue by SolayMane** [polinchen98/sequence-finder#2]
I have an error where runing blast.py as fellow :
````bash
python /home1/software/sequence-finder/src/blast.py --input salVaccinal.fna --db download/database_others/others --evalue 10 --num_threads 56 --task blastn

````
I get:
````bash
Traceback (most recent call last):
  File "/home1/software/sequence-finder/src/blast.py", line 18, in <module>
    Blast(args.input, args.db, args.output, args.format, args.evalue, args.num_threads, args.task)
  File "/home1/software/sequence-finder/src/logic/Blast.py", line 71, in __init__
    hits_file.write(q_dict[hit].format('fasta'))
  File "/home/inra/miniconda2/lib/python3.7/site-packages/Bio/File.py", line 227, in __getitem__
    record = self._proxy.get(self._offsets[key])
KeyError: 'No'
````

**Comment by polinchen98** [comment]
Thanks for your comment, I am glad that my program can be useful. I will try to figure it out with the error.
